/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.ucr.if3000.biblioteca.gui;

import cr.ac.ucr.if3000.biblioteca.domain.Biblioteca;
import cr.ac.ucr.if3000.biblioteca.domain.Catalogo;
import cr.ac.ucr.if3000.biblioteca.domain.Persona;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.nio.charset.CodingErrorAction;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ValeriaLeivaQuirós
 */
public class BuscarObra extends javax.swing.JFrame {
    
    Biblioteca biblioteca;
    DefaultTableModel modelo;
    TableRowSorter trs;
    Persona persona;
    String tipoInterfaz;

    /**
     * Creates new form Cátalogo
     */
    public BuscarObra() {
        modelo = new DefaultTableModel();
        biblioteca = new Biblioteca();
        
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        modelo.addColumn("codigo");
        modelo.addColumn("Titulo");
        modelo.addColumn("Fecha de Ingreso");
        modelo.addColumn("Autor");
        
        for (int i = 0; i < biblioteca.getCatalogos().size(); i++) {
            Catalogo catalogo = biblioteca.getCatalogos().get(i);
            modelo.addRow(new Object[]{catalogo.getCodigoCatalogo(), catalogo.getTitulo(), catalogo.getFechaIngreso(), catalogo.getAutor()});
            this.jTableListaObras.setModel(modelo);
            
        }
    }

    /**
     *
     * @param persona
     */
    public BuscarObra(Persona persona) {
        modelo = new DefaultTableModel();
        biblioteca = new Biblioteca();
        
        persona = persona;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        modelo.addColumn("codigo");
        modelo.addColumn("Titulo");
        modelo.addColumn("Fecha de Ingreso");
        modelo.addColumn("Autor");
        
        for (int i = 0; i < biblioteca.getCatalogos().size(); i++) {
            Catalogo catalogo = biblioteca.getCatalogos().get(i);
            
            if (catalogo.getAutor().getIdentificacion().equalsIgnoreCase(persona.getIdentificacion())) {
                modelo.addRow(new Object[]{catalogo.getCodigoCatalogo(), catalogo.getTitulo(), catalogo.getFechaIngreso(), catalogo.getAutor()});
            }
            this.jTableListaObras.setModel(modelo);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBuscarObra = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaObras = new javax.swing.JTable();
        jLabelBuscarPorTitulo = new javax.swing.JLabel();
        jTextFieldBuscarPorTitulo = new javax.swing.JTextField();
        jLabelBuscarPorAutor = new javax.swing.JLabel();
        jTextFieldBuscarPorAutor = new javax.swing.JTextField();
        jButtonRealizarPrestamo = new javax.swing.JButton();
        jButtonDevolucionDeObra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar Obra");

        jLabelBuscarObra.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabelBuscarObra.setForeground(new java.awt.Color(0, 51, 255));
        jLabelBuscarObra.setText("Buscar Obra");

        jTableListaObras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        jTableListaObras.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jTableListaObras.setForeground(new java.awt.Color(0, 51, 255));
        jTableListaObras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Tipo", "Titulo", "Autor", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTableListaObras);

        jLabelBuscarPorTitulo.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabelBuscarPorTitulo.setForeground(new java.awt.Color(0, 51, 255));
        jLabelBuscarPorTitulo.setText("Buscar obra por titulo:");

        jTextFieldBuscarPorTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        jTextFieldBuscarPorTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarPorTituloKeyTyped(evt);
            }
        });

        jLabelBuscarPorAutor.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabelBuscarPorAutor.setForeground(new java.awt.Color(0, 51, 255));
        jLabelBuscarPorAutor.setText("Buscar obra por autor:");

        jTextFieldBuscarPorAutor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));

        jButtonRealizarPrestamo.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonRealizarPrestamo.setForeground(new java.awt.Color(0, 51, 255));
        jButtonRealizarPrestamo.setText("Realizar Prestamo");
        jButtonRealizarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarPrestamoActionPerformed(evt);
            }
        });

        jButtonDevolucionDeObra.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonDevolucionDeObra.setForeground(new java.awt.Color(0, 51, 255));
        jButtonDevolucionDeObra.setText("Devolución de Obra");
        jButtonDevolucionDeObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevolucionDeObraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabelBuscarPorAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDevolucionDeObra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRealizarPrestamo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabelBuscarPorTitulo)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBuscarPorAutor)
                            .addComponent(jTextFieldBuscarPorTitulo))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelBuscarObra)
                .addGap(333, 333, 333))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelBuscarPorTitulo)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldBuscarPorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBuscarPorAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldBuscarPorAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRealizarPrestamo)
                    .addComponent(jButtonDevolucionDeObra))
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabelBuscarObra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRealizarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarPrestamoActionPerformed
        int codigo;
        codigo = ((int) modelo.getValueAt(jTableListaObras.getSelectedRow(), 0));
        
        System.out.println(codigo);
        
        RegistrarPrestamo registrarPrestamo = new RegistrarPrestamo(codigo);
        registrarPrestamo.setVisible(true);
        
        dispose();
        

    }//GEN-LAST:event_jButtonRealizarPrestamoActionPerformed

    private void jTextFieldBuscarPorTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarPorTituloKeyTyped
        jTextFieldBuscarPorTitulo.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                trs.setRowFilter(RowFilter.regexFilter(jTextFieldBuscarPorTitulo.getText(), 1));
            }
            
        });
        
        trs = new TableRowSorter(modelo);
        jTableListaObras.setRowSorter(trs);
    }//GEN-LAST:event_jTextFieldBuscarPorTituloKeyTyped

    private void jButtonDevolucionDeObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevolucionDeObraActionPerformed
        int codigo;
        codigo = ((int) modelo.getValueAt(jTableListaObras.getSelectedRow(), 0));
        
        DevoluciónDeObras devoluciónDeObras = new DevoluciónDeObras(biblioteca.buscarLibroPorCodigo(codigo));
        devoluciónDeObras.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonDevolucionDeObraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarObra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarObra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarObra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarObra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarObra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDevolucionDeObra;
    private javax.swing.JButton jButtonRealizarPrestamo;
    private javax.swing.JLabel jLabelBuscarObra;
    private javax.swing.JLabel jLabelBuscarPorAutor;
    private javax.swing.JLabel jLabelBuscarPorTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaObras;
    private javax.swing.JTextField jTextFieldBuscarPorAutor;
    private javax.swing.JTextField jTextFieldBuscarPorTitulo;
    // End of variables declaration//GEN-END:variables

}
