/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.ucr.if3000.biblioteca.gui;

import cr.ac.ucr.if3000.biblioteca.domain.Biblioteca;
import cr.ac.ucr.if3000.biblioteca.domain.Catalogo;
import cr.ac.ucr.if3000.biblioteca.domain.Persona;
import cr.ac.ucr.if3000.biblioteca.domain.Usuario;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ValeriaLeivaQuirós
 */
public class LibrosPrestados extends javax.swing.JFrame {

    DefaultTableModel tablaLibrosPrestados;
    Biblioteca biblioteca;
    Persona persona;
    String tipoInterafaz;

    public LibrosPrestados() {
        tablaLibrosPrestados = new DefaultTableModel();
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        biblioteca = new Biblioteca();

        tablaLibrosPrestados.addColumn("codigo");
        tablaLibrosPrestados.addColumn("Titulo");
        tablaLibrosPrestados.addColumn("Fecha de Ingreso");
        tablaLibrosPrestados.addColumn("Autor");

        for (int i = 0; i < biblioteca.catalogoPrestado().size(); i++) {
            Catalogo catalogo = biblioteca.getCatalogos().get(i);
            tablaLibrosPrestados.addRow(new Object[]{catalogo.getCodigoCatalogo(), catalogo.getTitulo(), catalogo.getFechaIngreso(), catalogo.getAutor()});
            this.jTableLibrosPrestados.setModel(tablaLibrosPrestados);
        }

    }

    public LibrosPrestados(Persona persona) {
        tablaLibrosPrestados = new DefaultTableModel();
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        biblioteca = new Biblioteca();

        tablaLibrosPrestados.addColumn("codigo");
        tablaLibrosPrestados.addColumn("Titulo");
        tablaLibrosPrestados.addColumn("Fecha de Ingreso");
        tablaLibrosPrestados.addColumn("Autor");

        for (int i = 0; i < biblioteca.catalogoPrestado().size(); i++) {
            Catalogo catalogo = biblioteca.getCatalogos().get(i);
            if (biblioteca.getCatalogos().get(i).getPrestamo().getPersona().getIdentificacion().equalsIgnoreCase(persona.getIdentificacion())) {
                tablaLibrosPrestados.addRow(new Object[]{catalogo.getCodigoCatalogo(), catalogo.getTitulo(), catalogo.getFechaIngreso(), catalogo.getAutor()});
            }
            this.jTableLibrosPrestados.setModel(tablaLibrosPrestados);
        }
        persona = persona;

        jLabelNombre.setText(persona.getNombreUnico());
        jLabelCedula.setText(persona.getIdentificacion());

    }

    public LibrosPrestados(Persona persona, String tipo) {
        tablaLibrosPrestados = new DefaultTableModel();
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        biblioteca = new Biblioteca();
        tipoInterafaz = tipo;

        tablaLibrosPrestados.addColumn("codigo");
        tablaLibrosPrestados.addColumn("Titulo");
        tablaLibrosPrestados.addColumn("Fecha de Ingreso");
        tablaLibrosPrestados.addColumn("Autor");

        for (int i = 0; i < biblioteca.catalogoPrestado().size(); i++) {
            Catalogo catalogo = biblioteca.getCatalogos().get(i);
            if (biblioteca.getCatalogos().get(i).getPrestamo().getPersona().getIdentificacion().equalsIgnoreCase(persona.getIdentificacion())) {
                tablaLibrosPrestados.addRow(new Object[]{catalogo.getCodigoCatalogo(), catalogo.getTitulo(), catalogo.getFechaIngreso(), catalogo.getAutor()});
            }
            this.jTableLibrosPrestados.setModel(tablaLibrosPrestados);
        }
        persona = persona;

        jLabelNombre.setText(persona.getNombreUnico());
        jLabelCedula.setText(persona.getIdentificacion());
        jButtonBuscarUsuario.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabelLibrosPrestados = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonBuscarUsuario = new javax.swing.JButton();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelIdentificacion = new javax.swing.JLabel();
        jLabelCedula = new javax.swing.JLabel();
        jButtonDevolverLibro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLibrosPrestados = new javax.swing.JTable();
        jButtonVolver = new javax.swing.JButton();

        jLabel7.setText("jLabel7");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Libros Prestados");

        jLabelLibrosPrestados.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabelLibrosPrestados.setForeground(new java.awt.Color(0, 51, 255));
        jLabelLibrosPrestados.setText("Libros Prestados");

        jButtonBuscarUsuario.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonBuscarUsuario.setForeground(new java.awt.Color(0, 51, 255));
        jButtonBuscarUsuario.setText("Buscar Usuario");
        jButtonBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarUsuarioActionPerformed(evt);
            }
        });

        jLabelNombreUsuario.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabelNombreUsuario.setForeground(new java.awt.Color(0, 51, 255));
        jLabelNombreUsuario.setText("Nombre de Usuario:");

        jLabelIdentificacion.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabelIdentificacion.setForeground(new java.awt.Color(0, 51, 255));
        jLabelIdentificacion.setText("Identificación:");

        jButtonDevolverLibro.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonDevolverLibro.setForeground(new java.awt.Color(0, 51, 255));
        jButtonDevolverLibro.setText("Devolver Libro");
        jButtonDevolverLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevolverLibroActionPerformed(evt);
            }
        });

        jTableLibrosPrestados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        jTableLibrosPrestados.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jTableLibrosPrestados.setForeground(new java.awt.Color(0, 51, 255));
        jTableLibrosPrestados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Tipo", "Titulo", "Autor", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTableLibrosPrestados);

        jButtonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cr/ac/ucr/if3000/biblioteca/Imagenes/sign-out.png"))); // NOI18N
        jButtonVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNombreUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelIdentificacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDevolverLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBuscarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(308, 308, 308)
                        .addComponent(jLabelLibrosPrestados)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabelLibrosPrestados))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombreUsuario)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelIdentificacion)
                            .addComponent(jLabelCedula))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(294, 294, 294)
                                .addComponent(jButtonBuscarUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDevolverLibro))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarUsuarioActionPerformed
        BuscarUsuario buscarUsuario = new BuscarUsuario("LibrosPrestados");
        buscarUsuario.setVisible(true);
    }//GEN-LAST:event_jButtonBuscarUsuarioActionPerformed

    private void jButtonDevolverLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevolverLibroActionPerformed
        DevoluciónDeObras devoluciónDeObras = new DevoluciónDeObras();
        devoluciónDeObras.setVisible(true);
    }//GEN-LAST:event_jButtonDevolverLibroActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        
        if (tipoInterafaz.equalsIgnoreCase("MenuUsuario")) {
            MenuUsuario menuUsuario = new MenuUsuario();
            menuUsuario.setVisible(true);
            dispose();

        }
    }//GEN-LAST:event_jButtonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrosPrestados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrosPrestados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrosPrestados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrosPrestados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrosPrestados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarUsuario;
    private javax.swing.JButton jButtonDevolverLibro;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelIdentificacion;
    private javax.swing.JLabel jLabelLibrosPrestados;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLibrosPrestados;
    // End of variables declaration//GEN-END:variables
}
